//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Desktop.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UI.Desktop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1486564394_edit_81508 {
            get {
                object obj = ResourceManager.GetObject("1486564394-edit_81508", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _353430_checkbox_edit_pen_pencil_107516 {
            get {
                object obj = ResourceManager.GetObject("353430-checkbox-edit-pen-pencil_107516", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3615751_banknote_cash_cheque_money_order_payment_voucher_107903 {
            get {
                object obj = ResourceManager.GetObject("3615751-banknote-cash-cheque-money-order-payment-voucher_107903", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3706883_control_music_pause_stop_stop_music_108702 {
            get {
                object obj = ResourceManager.GetObject("3706883-control-music-pause-stop-stop-music_108702", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3925411_cashbox_cashier_shop_icon_111535 {
            get {
                object obj = ResourceManager.GetObject("3925411-cashbox-cashier-shop-icon_111535", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap addthelist_añadir_3477 {
            get {
                object obj = ResourceManager.GetObject("addthelist_añadir_3477", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap adduser_añadir_3553 {
            get {
                object obj = ResourceManager.GetObject("adduser_añadir_3553", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bill_payment_note_icon_143283 {
            get {
                object obj = ResourceManager.GetObject("bill_payment_note_icon_143283", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;Comprobante lavado&lt;/title&gt;
        ///	&lt;style&gt;
        ///		table.border {
        ///			border-collapse: collapse;
        ///			border: 1px solid black;
        ///		}
        ///
        ///	&lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;font size=&quot;2&quot;&gt;
        ///		&lt;table align=&quot;center&quot; cellspacing=1 cellpadding=1&gt;
        ///			&lt;tr&gt;
        ///				&lt;td&gt;
        ///					&lt;table class=&quot;border&quot;&gt;
        ///						&lt;tr&gt;
        ///							&lt;td style=&quot;width:75%&quot;&gt;
        ///								&lt;table&gt;
        ///									&lt;tr&gt;&lt;td&gt;&lt;font size=&quot;5&quot;&gt;@NombreLavanderia&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;
        ///									&lt;tr&gt;&lt;td&gt;@DireccionLav&lt;/td&gt;&lt;/tr&gt;
        ///									&lt;tr&gt;&lt;td&gt;Tel:@TelLav&lt;/ [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string comprobanteorden2 {
            get {
                return ResourceManager.GetString("comprobanteorden2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap customer_service_icon_194124 {
            get {
                object obj = ResourceManager.GetObject("customer_service_icon_194124", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap document_3530 {
            get {
                object obj = ResourceManager.GetObject("document_3530", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap effective_employees_users_team_group_icon_152042 {
            get {
                object obj = ResourceManager.GetObject("effective_employees_users_team_group_icon_152042", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap electric_appliances_waching_machine_laundry_icon_124437 {
            get {
                object obj = ResourceManager.GetObject("electric_appliances_waching_machine_laundry_icon_124437", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;Comprobante de Retiro&lt;/title&gt;
        ///	&lt;style&gt;
        ///		table.border {
        ///			border-collapse: collapse;
        ///			border: 1px solid black;
        ///			
        ///			
        ///		}
        ///		
        ///		table tbody{
        ///			border-collapse: collapse;
        ///			border: 1px solid black;
        ///			
        ///		}
        ///		table th {
        ///		    border:1px solid black;
        ///		}
        ///	&lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;table class=&quot;border&quot; style=&quot;width:100%&quot;&gt;
        ///		&lt;tr&gt;
        ///			
        ///			&lt;td&gt;
        ///				&lt;table align=&quot;left&quot;&gt;
        ///					&lt;tr&gt;
        ///						&lt;td align=&quot;center&quot;&gt;&lt;font size=&quot;5&quot;&gt;@nombrempresa&lt;/font&gt;&lt;/td&gt;        /// [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string factura {
            get {
                return ResourceManager.GetString("factura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hide_icon_183908 {
            get {
                object obj = ResourceManager.GetObject("hide_icon_183908", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap laundry_washing_machine_clothes_clean_wash_icon_196779 {
            get {
                object obj = ResourceManager.GetObject("laundry_washing_machine_clothes_clean_wash_icon_196779", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap laundry_washing_machine_clothes_clean_wash_icon_196809 {
            get {
                object obj = ResourceManager.GetObject("laundry_washing_machine_clothes_clean_wash_icon_196809", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap laundry_washing_machine_clothes_clean_wash_icon_196839 {
            get {
                object obj = ResourceManager.GetObject("laundry_washing_machine_clothes_clean_wash_icon_196839", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap laundry_washing_machine_clothes_clean_wash_icon_196839__1_ {
            get {
                object obj = ResourceManager.GetObject("laundry_washing_machine_clothes_clean_wash_icon_196839 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mbriprint_99560 {
            get {
                object obj = ResourceManager.GetObject("mbriprint_99560", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap multimediamusicplayerplaybutton_85798 {
            get {
                object obj = ResourceManager.GetObject("multimediamusicplayerplaybutton_85798", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap navigation_find_location_icon_220679 {
            get {
                object obj = ResourceManager.GetObject("navigation_find_location_icon_220679", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap new_add_user_16734 {
            get {
                object obj = ResourceManager.GetObject("new_add_user_16734", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap off_log_icon_214125 {
            get {
                object obj = ResourceManager.GetObject("off_log_icon_214125", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pay_payment_bill_dollar_cash_icon_143281 {
            get {
                object obj = ResourceManager.GetObject("pay_payment_bill_dollar_cash_icon_143281", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paying_money_invoice_payment_your_bill_icon_220368 {
            get {
                object obj = ResourceManager.GetObject("paying_money_invoice_payment_your_bill_icon_220368", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap payment_tax_invoice_document_calculator_icon_188684 {
            get {
                object obj = ResourceManager.GetObject("payment_tax_invoice_document_calculator_icon_188684", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap payment_tax_invoice_document_calculator_icon_188684__1_ {
            get {
                object obj = ResourceManager.GetObject("payment_tax_invoice_document_calculator_icon_188684 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap play_button_icon_icons_com_70891 {
            get {
                object obj = ResourceManager.GetObject("play-button_icon-icons.com_70891", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap play_circle_icon_icons_com_69988 {
            get {
                object obj = ResourceManager.GetObject("play-circle_icon-icons.com_69988", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap play_circle_icon_icons1 {
            get {
                object obj = ResourceManager.GetObject("play-circle_icon-icons1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap playbutton_120627 {
            get {
                object obj = ResourceManager.GetObject("playbutton_120627", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap playwithcircularbuttonwithrightarrowofboldroundedfilledtriangle_80162 {
            get {
                object obj = ResourceManager.GetObject("playwithcircularbuttonwithrightarrowofboldroundedfilledtriangle_80162", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap plus_icon_icons_com_70890 {
            get {
                object obj = ResourceManager.GetObject("plus_icon-icons.com_70890", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap power_on_off_log_out_exit_icon_141949 {
            get {
                object obj = ResourceManager.GetObject("power_on_off_log_out_exit_icon_141949", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap product_delivery_icon_152013 {
            get {
                object obj = ResourceManager.GetObject("product_delivery_icon_152013", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap productapplication_producto_3010 {
            get {
                object obj = ResourceManager.GetObject("productapplication_producto_3010", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap report_document_finance_business_analysis_analytics_chart_icon_188615 {
            get {
                object obj = ResourceManager.GetObject("report_document_finance_business_analysis_analytics_chart_icon_188615", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap round_account_button_with_user_inside_icon_icons_com_72596 {
            get {
                object obj = ResourceManager.GetObject("round-account-button-with-user-inside_icon-icons.com_72596", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search_find_look_zoom_in_icon_icons_com_59897 {
            get {
                object obj = ResourceManager.GetObject("search_find_look_zoom_in_icon-icons.com_59897", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search_find_user_16727 {
            get {
                object obj = ResourceManager.GetObject("search_find_user_16727", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap searcher_magnifyng_glass_search_locate_find_icon_123813 {
            get {
                object obj = ResourceManager.GetObject("searcher_magnifyng_glass_search_locate_find_icon_123813", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap show_icon_215343 {
            get {
                object obj = ResourceManager.GetObject("show_icon_215343", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap squareinsideacircle_120602 {
            get {
                object obj = ResourceManager.GetObject("squareinsideacircle_120602", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stop_button_icon_icons_com_71563 {
            get {
                object obj = ResourceManager.GetObject("stop-button_icon-icons.com_71563", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap thefreeforty_withdraw_icon_icons_com_66307 {
            get {
                object obj = ResourceManager.GetObject("thefreeforty_withdraw_icon-icons.com_66307", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap trash_bin_icon_icons_com_67981 {
            get {
                object obj = ResourceManager.GetObject("trash_bin_icon-icons.com_67981", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tshirt_120689 {
            get {
                object obj = ResourceManager.GetObject("tshirt_120689", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap view_show_icon_124811 {
            get {
                object obj = ResourceManager.GetObject("view_show_icon_124811", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap washing_machine_washer_cloth_cloths_laundry_appliances_icon_icons_com_53502 {
            get {
                object obj = ResourceManager.GetObject("washing_machine_washer_cloth_cloths_laundry_appliances_icon-icons.com_53502", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap worker_form_document_icon_208910 {
            get {
                object obj = ResourceManager.GetObject("worker_form_document_icon_208910", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
